// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/broker.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	MessageId            int64    `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	CheckSum             int32    `protobuf:"varint,2,opt,name=checkSum,proto3" json:"checkSum,omitempty"`
	PayLoadData          []byte   `protobuf:"bytes,3,opt,name=payLoadData,proto3" json:"payLoadData,omitempty"`
	Flag                 int32    `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Message) GetCheckSum() int32 {
	if m != nil {
		return m.CheckSum
	}
	return 0
}

func (m *Message) GetPayLoadData() []byte {
	if m != nil {
		return m.PayLoadData
	}
	return nil
}

func (m *Message) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type AuthorizedInfo struct {
	VisitAuthorizedToken int64    `protobuf:"varint,1,opt,name=visitAuthorizedToken,proto3" json:"visitAuthorizedToken,omitempty"`
	AuthAuthorizedToken  string   `protobuf:"bytes,2,opt,name=authAuthorizedToken,proto3" json:"authAuthorizedToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizedInfo) Reset()         { *m = AuthorizedInfo{} }
func (m *AuthorizedInfo) String() string { return proto.CompactTextString(m) }
func (*AuthorizedInfo) ProtoMessage()    {}
func (*AuthorizedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{1}
}

func (m *AuthorizedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizedInfo.Unmarshal(m, b)
}
func (m *AuthorizedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizedInfo.Marshal(b, m, deterministic)
}
func (m *AuthorizedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizedInfo.Merge(m, src)
}
func (m *AuthorizedInfo) XXX_Size() int {
	return xxx_messageInfo_AuthorizedInfo.Size(m)
}
func (m *AuthorizedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizedInfo proto.InternalMessageInfo

func (m *AuthorizedInfo) GetVisitAuthorizedToken() int64 {
	if m != nil {
		return m.VisitAuthorizedToken
	}
	return 0
}

func (m *AuthorizedInfo) GetAuthAuthorizedToken() string {
	if m != nil {
		return m.AuthAuthorizedToken
	}
	return ""
}

type SendMessageRequestP2B struct {
	ClientId             string          `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	TopicName            string          `protobuf:"bytes,2,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionId          int32           `protobuf:"varint,3,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Data                 []byte          `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Flag                 int32           `protobuf:"varint,5,opt,name=flag,proto3" json:"flag,omitempty"`
	CheckSum             int32           `protobuf:"varint,6,opt,name=checkSum,proto3" json:"checkSum,omitempty"`
	SentAddr             int32           `protobuf:"varint,7,opt,name=sentAddr,proto3" json:"sentAddr,omitempty"`
	MsgType              string          `protobuf:"bytes,8,opt,name=msgType,proto3" json:"msgType,omitempty"`
	MsgTime              string          `protobuf:"bytes,9,opt,name=msgTime,proto3" json:"msgTime,omitempty"`
	AuthInfo             *AuthorizedInfo `protobuf:"bytes,10,opt,name=authInfo,proto3" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SendMessageRequestP2B) Reset()         { *m = SendMessageRequestP2B{} }
func (m *SendMessageRequestP2B) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequestP2B) ProtoMessage()    {}
func (*SendMessageRequestP2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{2}
}

func (m *SendMessageRequestP2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequestP2B.Unmarshal(m, b)
}
func (m *SendMessageRequestP2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequestP2B.Marshal(b, m, deterministic)
}
func (m *SendMessageRequestP2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequestP2B.Merge(m, src)
}
func (m *SendMessageRequestP2B) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequestP2B.Size(m)
}
func (m *SendMessageRequestP2B) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequestP2B.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequestP2B proto.InternalMessageInfo

func (m *SendMessageRequestP2B) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *SendMessageRequestP2B) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *SendMessageRequestP2B) GetPartitionId() int32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *SendMessageRequestP2B) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SendMessageRequestP2B) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *SendMessageRequestP2B) GetCheckSum() int32 {
	if m != nil {
		return m.CheckSum
	}
	return 0
}

func (m *SendMessageRequestP2B) GetSentAddr() int32 {
	if m != nil {
		return m.SentAddr
	}
	return 0
}

func (m *SendMessageRequestP2B) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *SendMessageRequestP2B) GetMsgTime() string {
	if m != nil {
		return m.MsgTime
	}
	return ""
}

func (m *SendMessageRequestP2B) GetAuthInfo() *AuthorizedInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type SendMessageResponseB2P struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrCode              int32    `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	RequireAuth          bool     `protobuf:"varint,4,opt,name=requireAuth,proto3" json:"requireAuth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponseB2P) Reset()         { *m = SendMessageResponseB2P{} }
func (m *SendMessageResponseB2P) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponseB2P) ProtoMessage()    {}
func (*SendMessageResponseB2P) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{3}
}

func (m *SendMessageResponseB2P) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponseB2P.Unmarshal(m, b)
}
func (m *SendMessageResponseB2P) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponseB2P.Marshal(b, m, deterministic)
}
func (m *SendMessageResponseB2P) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponseB2P.Merge(m, src)
}
func (m *SendMessageResponseB2P) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponseB2P.Size(m)
}
func (m *SendMessageResponseB2P) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponseB2P.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponseB2P proto.InternalMessageInfo

func (m *SendMessageResponseB2P) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendMessageResponseB2P) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *SendMessageResponseB2P) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *SendMessageResponseB2P) GetRequireAuth() bool {
	if m != nil {
		return m.RequireAuth
	}
	return false
}

type RegisterRequestC2B struct {
	OpType               int32           `protobuf:"varint,1,opt,name=opType,proto3" json:"opType,omitempty"`
	ClientId             string          `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	GroupName            string          `protobuf:"bytes,3,opt,name=groupName,proto3" json:"groupName,omitempty"`
	TopicName            string          `protobuf:"bytes,4,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionId          int32           `protobuf:"varint,5,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	ReadStatus           int32           `protobuf:"varint,6,opt,name=readStatus,proto3" json:"readStatus,omitempty"`
	FilterCondStr        []string        `protobuf:"bytes,7,rep,name=filterCondStr,proto3" json:"filterCondStr,omitempty"`
	CurrOffset           int64           `protobuf:"varint,8,opt,name=currOffset,proto3" json:"currOffset,omitempty"`
	SessionKey           string          `protobuf:"bytes,9,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	SessionTime          int64           `protobuf:"varint,10,opt,name=sessionTime,proto3" json:"sessionTime,omitempty"`
	SsdStoreId           int64           `protobuf:"varint,11,opt,name=ssdStoreId,proto3" json:"ssdStoreId,omitempty"`
	QryPriorityId        int32           `protobuf:"varint,12,opt,name=qryPriorityId,proto3" json:"qryPriorityId,omitempty"`
	AuthInfo             *AuthorizedInfo `protobuf:"bytes,13,opt,name=authInfo,proto3" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RegisterRequestC2B) Reset()         { *m = RegisterRequestC2B{} }
func (m *RegisterRequestC2B) String() string { return proto.CompactTextString(m) }
func (*RegisterRequestC2B) ProtoMessage()    {}
func (*RegisterRequestC2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{4}
}

func (m *RegisterRequestC2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequestC2B.Unmarshal(m, b)
}
func (m *RegisterRequestC2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequestC2B.Marshal(b, m, deterministic)
}
func (m *RegisterRequestC2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequestC2B.Merge(m, src)
}
func (m *RegisterRequestC2B) XXX_Size() int {
	return xxx_messageInfo_RegisterRequestC2B.Size(m)
}
func (m *RegisterRequestC2B) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequestC2B.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequestC2B proto.InternalMessageInfo

func (m *RegisterRequestC2B) GetOpType() int32 {
	if m != nil {
		return m.OpType
	}
	return 0
}

func (m *RegisterRequestC2B) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RegisterRequestC2B) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *RegisterRequestC2B) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *RegisterRequestC2B) GetPartitionId() int32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *RegisterRequestC2B) GetReadStatus() int32 {
	if m != nil {
		return m.ReadStatus
	}
	return 0
}

func (m *RegisterRequestC2B) GetFilterCondStr() []string {
	if m != nil {
		return m.FilterCondStr
	}
	return nil
}

func (m *RegisterRequestC2B) GetCurrOffset() int64 {
	if m != nil {
		return m.CurrOffset
	}
	return 0
}

func (m *RegisterRequestC2B) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

func (m *RegisterRequestC2B) GetSessionTime() int64 {
	if m != nil {
		return m.SessionTime
	}
	return 0
}

func (m *RegisterRequestC2B) GetSsdStoreId() int64 {
	if m != nil {
		return m.SsdStoreId
	}
	return 0
}

func (m *RegisterRequestC2B) GetQryPriorityId() int32 {
	if m != nil {
		return m.QryPriorityId
	}
	return 0
}

func (m *RegisterRequestC2B) GetAuthInfo() *AuthorizedInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type RegisterResponseB2C struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrCode              int32    `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	CurrOffset           int64    `protobuf:"varint,4,opt,name=currOffset,proto3" json:"currOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponseB2C) Reset()         { *m = RegisterResponseB2C{} }
func (m *RegisterResponseB2C) String() string { return proto.CompactTextString(m) }
func (*RegisterResponseB2C) ProtoMessage()    {}
func (*RegisterResponseB2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{5}
}

func (m *RegisterResponseB2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponseB2C.Unmarshal(m, b)
}
func (m *RegisterResponseB2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponseB2C.Marshal(b, m, deterministic)
}
func (m *RegisterResponseB2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponseB2C.Merge(m, src)
}
func (m *RegisterResponseB2C) XXX_Size() int {
	return xxx_messageInfo_RegisterResponseB2C.Size(m)
}
func (m *RegisterResponseB2C) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponseB2C.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponseB2C proto.InternalMessageInfo

func (m *RegisterResponseB2C) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterResponseB2C) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *RegisterResponseB2C) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *RegisterResponseB2C) GetCurrOffset() int64 {
	if m != nil {
		return m.CurrOffset
	}
	return 0
}

type HeartBeatRequestC2B struct {
	ClientId   string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	GroupName  string `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ReadStatus int32  `protobuf:"varint,3,opt,name=readStatus,proto3" json:"readStatus,omitempty"`
	// brokerId:host:port:topic:partitionId:delayTimeStamp
	PartitionInfo        []string        `protobuf:"bytes,4,rep,name=partitionInfo,proto3" json:"partitionInfo,omitempty"`
	SsdStoreId           int64           `protobuf:"varint,5,opt,name=ssdStoreId,proto3" json:"ssdStoreId,omitempty"`
	QryPriorityId        int32           `protobuf:"varint,6,opt,name=qryPriorityId,proto3" json:"qryPriorityId,omitempty"`
	AuthInfo             *AuthorizedInfo `protobuf:"bytes,7,opt,name=authInfo,proto3" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HeartBeatRequestC2B) Reset()         { *m = HeartBeatRequestC2B{} }
func (m *HeartBeatRequestC2B) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRequestC2B) ProtoMessage()    {}
func (*HeartBeatRequestC2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{6}
}

func (m *HeartBeatRequestC2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRequestC2B.Unmarshal(m, b)
}
func (m *HeartBeatRequestC2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRequestC2B.Marshal(b, m, deterministic)
}
func (m *HeartBeatRequestC2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRequestC2B.Merge(m, src)
}
func (m *HeartBeatRequestC2B) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRequestC2B.Size(m)
}
func (m *HeartBeatRequestC2B) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRequestC2B.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRequestC2B proto.InternalMessageInfo

func (m *HeartBeatRequestC2B) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *HeartBeatRequestC2B) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *HeartBeatRequestC2B) GetReadStatus() int32 {
	if m != nil {
		return m.ReadStatus
	}
	return 0
}

func (m *HeartBeatRequestC2B) GetPartitionInfo() []string {
	if m != nil {
		return m.PartitionInfo
	}
	return nil
}

func (m *HeartBeatRequestC2B) GetSsdStoreId() int64 {
	if m != nil {
		return m.SsdStoreId
	}
	return 0
}

func (m *HeartBeatRequestC2B) GetQryPriorityId() int32 {
	if m != nil {
		return m.QryPriorityId
	}
	return 0
}

func (m *HeartBeatRequestC2B) GetAuthInfo() *AuthorizedInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type HeartBeatResponseB2C struct {
	Success        bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrCode        int32  `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg         string `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	HasPartFailure bool   `protobuf:"varint,4,opt,name=hasPartFailure,proto3" json:"hasPartFailure,omitempty"`
	// failCode:brokerId:host:port:topic:partitionId:delayTimeStamp
	FailureInfo          []string `protobuf:"bytes,5,rep,name=failureInfo,proto3" json:"failureInfo,omitempty"`
	RequireAuth          bool     `protobuf:"varint,6,opt,name=requireAuth,proto3" json:"requireAuth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatResponseB2C) Reset()         { *m = HeartBeatResponseB2C{} }
func (m *HeartBeatResponseB2C) String() string { return proto.CompactTextString(m) }
func (*HeartBeatResponseB2C) ProtoMessage()    {}
func (*HeartBeatResponseB2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{7}
}

func (m *HeartBeatResponseB2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatResponseB2C.Unmarshal(m, b)
}
func (m *HeartBeatResponseB2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatResponseB2C.Marshal(b, m, deterministic)
}
func (m *HeartBeatResponseB2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatResponseB2C.Merge(m, src)
}
func (m *HeartBeatResponseB2C) XXX_Size() int {
	return xxx_messageInfo_HeartBeatResponseB2C.Size(m)
}
func (m *HeartBeatResponseB2C) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatResponseB2C.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatResponseB2C proto.InternalMessageInfo

func (m *HeartBeatResponseB2C) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *HeartBeatResponseB2C) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *HeartBeatResponseB2C) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *HeartBeatResponseB2C) GetHasPartFailure() bool {
	if m != nil {
		return m.HasPartFailure
	}
	return false
}

func (m *HeartBeatResponseB2C) GetFailureInfo() []string {
	if m != nil {
		return m.FailureInfo
	}
	return nil
}

func (m *HeartBeatResponseB2C) GetRequireAuth() bool {
	if m != nil {
		return m.RequireAuth
	}
	return false
}

type GetMessageRequestC2B struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	PartitionId          int32    `protobuf:"varint,2,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	GroupName            string   `protobuf:"bytes,3,opt,name=groupName,proto3" json:"groupName,omitempty"`
	TopicName            string   `protobuf:"bytes,4,opt,name=topicName,proto3" json:"topicName,omitempty"`
	LastPackConsumed     bool     `protobuf:"varint,5,opt,name=lastPackConsumed,proto3" json:"lastPackConsumed,omitempty"`
	ManualCommitOffset   bool     `protobuf:"varint,6,opt,name=manualCommitOffset,proto3" json:"manualCommitOffset,omitempty"`
	EscFlowCtrl          bool     `protobuf:"varint,7,opt,name=escFlowCtrl,proto3" json:"escFlowCtrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageRequestC2B) Reset()         { *m = GetMessageRequestC2B{} }
func (m *GetMessageRequestC2B) String() string { return proto.CompactTextString(m) }
func (*GetMessageRequestC2B) ProtoMessage()    {}
func (*GetMessageRequestC2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{8}
}

func (m *GetMessageRequestC2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRequestC2B.Unmarshal(m, b)
}
func (m *GetMessageRequestC2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRequestC2B.Marshal(b, m, deterministic)
}
func (m *GetMessageRequestC2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRequestC2B.Merge(m, src)
}
func (m *GetMessageRequestC2B) XXX_Size() int {
	return xxx_messageInfo_GetMessageRequestC2B.Size(m)
}
func (m *GetMessageRequestC2B) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRequestC2B.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRequestC2B proto.InternalMessageInfo

func (m *GetMessageRequestC2B) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GetMessageRequestC2B) GetPartitionId() int32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *GetMessageRequestC2B) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *GetMessageRequestC2B) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *GetMessageRequestC2B) GetLastPackConsumed() bool {
	if m != nil {
		return m.LastPackConsumed
	}
	return false
}

func (m *GetMessageRequestC2B) GetManualCommitOffset() bool {
	if m != nil {
		return m.ManualCommitOffset
	}
	return false
}

func (m *GetMessageRequestC2B) GetEscFlowCtrl() bool {
	if m != nil {
		return m.EscFlowCtrl
	}
	return false
}

type GetMessageResponseB2C struct {
	Success              bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrCode              int32      `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string     `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Messages             []*Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	CurrOffset           int64      `protobuf:"varint,5,opt,name=currOffset,proto3" json:"currOffset,omitempty"`
	MinLimitTime         int32      `protobuf:"varint,6,opt,name=minLimitTime,proto3" json:"minLimitTime,omitempty"`
	EscFlowCtrl          bool       `protobuf:"varint,7,opt,name=escFlowCtrl,proto3" json:"escFlowCtrl,omitempty"`
	CurrDataDlt          int64      `protobuf:"varint,8,opt,name=currDataDlt,proto3" json:"currDataDlt,omitempty"`
	RequireSlow          bool       `protobuf:"varint,9,opt,name=requireSlow,proto3" json:"requireSlow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMessageResponseB2C) Reset()         { *m = GetMessageResponseB2C{} }
func (m *GetMessageResponseB2C) String() string { return proto.CompactTextString(m) }
func (*GetMessageResponseB2C) ProtoMessage()    {}
func (*GetMessageResponseB2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{9}
}

func (m *GetMessageResponseB2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageResponseB2C.Unmarshal(m, b)
}
func (m *GetMessageResponseB2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageResponseB2C.Marshal(b, m, deterministic)
}
func (m *GetMessageResponseB2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageResponseB2C.Merge(m, src)
}
func (m *GetMessageResponseB2C) XXX_Size() int {
	return xxx_messageInfo_GetMessageResponseB2C.Size(m)
}
func (m *GetMessageResponseB2C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageResponseB2C.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageResponseB2C proto.InternalMessageInfo

func (m *GetMessageResponseB2C) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetMessageResponseB2C) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GetMessageResponseB2C) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetMessageResponseB2C) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *GetMessageResponseB2C) GetCurrOffset() int64 {
	if m != nil {
		return m.CurrOffset
	}
	return 0
}

func (m *GetMessageResponseB2C) GetMinLimitTime() int32 {
	if m != nil {
		return m.MinLimitTime
	}
	return 0
}

func (m *GetMessageResponseB2C) GetEscFlowCtrl() bool {
	if m != nil {
		return m.EscFlowCtrl
	}
	return false
}

func (m *GetMessageResponseB2C) GetCurrDataDlt() int64 {
	if m != nil {
		return m.CurrDataDlt
	}
	return 0
}

func (m *GetMessageResponseB2C) GetRequireSlow() bool {
	if m != nil {
		return m.RequireSlow
	}
	return false
}

type CommitOffsetRequestC2B struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionId          int32    `protobuf:"varint,3,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	GroupName            string   `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	LastPackConsumed     bool     `protobuf:"varint,5,opt,name=lastPackConsumed,proto3" json:"lastPackConsumed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitOffsetRequestC2B) Reset()         { *m = CommitOffsetRequestC2B{} }
func (m *CommitOffsetRequestC2B) String() string { return proto.CompactTextString(m) }
func (*CommitOffsetRequestC2B) ProtoMessage()    {}
func (*CommitOffsetRequestC2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{10}
}

func (m *CommitOffsetRequestC2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitOffsetRequestC2B.Unmarshal(m, b)
}
func (m *CommitOffsetRequestC2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitOffsetRequestC2B.Marshal(b, m, deterministic)
}
func (m *CommitOffsetRequestC2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitOffsetRequestC2B.Merge(m, src)
}
func (m *CommitOffsetRequestC2B) XXX_Size() int {
	return xxx_messageInfo_CommitOffsetRequestC2B.Size(m)
}
func (m *CommitOffsetRequestC2B) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitOffsetRequestC2B.DiscardUnknown(m)
}

var xxx_messageInfo_CommitOffsetRequestC2B proto.InternalMessageInfo

func (m *CommitOffsetRequestC2B) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *CommitOffsetRequestC2B) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *CommitOffsetRequestC2B) GetPartitionId() int32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *CommitOffsetRequestC2B) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *CommitOffsetRequestC2B) GetLastPackConsumed() bool {
	if m != nil {
		return m.LastPackConsumed
	}
	return false
}

type CommitOffsetResponseB2C struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrCode              int32    `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	CurrOffset           int64    `protobuf:"varint,4,opt,name=currOffset,proto3" json:"currOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitOffsetResponseB2C) Reset()         { *m = CommitOffsetResponseB2C{} }
func (m *CommitOffsetResponseB2C) String() string { return proto.CompactTextString(m) }
func (*CommitOffsetResponseB2C) ProtoMessage()    {}
func (*CommitOffsetResponseB2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_4936287245741274, []int{11}
}

func (m *CommitOffsetResponseB2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitOffsetResponseB2C.Unmarshal(m, b)
}
func (m *CommitOffsetResponseB2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitOffsetResponseB2C.Marshal(b, m, deterministic)
}
func (m *CommitOffsetResponseB2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitOffsetResponseB2C.Merge(m, src)
}
func (m *CommitOffsetResponseB2C) XXX_Size() int {
	return xxx_messageInfo_CommitOffsetResponseB2C.Size(m)
}
func (m *CommitOffsetResponseB2C) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitOffsetResponseB2C.DiscardUnknown(m)
}

var xxx_messageInfo_CommitOffsetResponseB2C proto.InternalMessageInfo

func (m *CommitOffsetResponseB2C) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CommitOffsetResponseB2C) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CommitOffsetResponseB2C) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CommitOffsetResponseB2C) GetCurrOffset() int64 {
	if m != nil {
		return m.CurrOffset
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "protocol.Message")
	proto.RegisterType((*AuthorizedInfo)(nil), "protocol.AuthorizedInfo")
	proto.RegisterType((*SendMessageRequestP2B)(nil), "protocol.SendMessageRequestP2B")
	proto.RegisterType((*SendMessageResponseB2P)(nil), "protocol.SendMessageResponseB2P")
	proto.RegisterType((*RegisterRequestC2B)(nil), "protocol.RegisterRequestC2B")
	proto.RegisterType((*RegisterResponseB2C)(nil), "protocol.RegisterResponseB2C")
	proto.RegisterType((*HeartBeatRequestC2B)(nil), "protocol.HeartBeatRequestC2B")
	proto.RegisterType((*HeartBeatResponseB2C)(nil), "protocol.HeartBeatResponseB2C")
	proto.RegisterType((*GetMessageRequestC2B)(nil), "protocol.GetMessageRequestC2B")
	proto.RegisterType((*GetMessageResponseB2C)(nil), "protocol.GetMessageResponseB2C")
	proto.RegisterType((*CommitOffsetRequestC2B)(nil), "protocol.CommitOffsetRequestC2B")
	proto.RegisterType((*CommitOffsetResponseB2C)(nil), "protocol.CommitOffsetResponseB2C")
}

func init() { proto.RegisterFile("protocol/broker.proto", fileDescriptor_4936287245741274) }

var fileDescriptor_4936287245741274 = []byte{
	// 890 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x96, 0x9d, 0x9f, 0x75, 0xce, 0x6e, 0x2b, 0xf0, 0xfe, 0x60, 0x55, 0x08, 0x45, 0x16, 0x42,
	0x11, 0xd2, 0x66, 0xab, 0xc0, 0x0b, 0x34, 0xa9, 0x0a, 0x2b, 0x5a, 0x88, 0x26, 0xbd, 0xe2, 0x6e,
	0xd6, 0x3e, 0xf1, 0x8e, 0x62, 0x7b, 0x92, 0x99, 0x71, 0xab, 0x70, 0xc7, 0x05, 0x5c, 0x22, 0xf1,
	0x3e, 0xc0, 0x03, 0x70, 0xc1, 0x33, 0xa1, 0x19, 0xdb, 0xf1, 0x4f, 0x22, 0x65, 0x51, 0xa9, 0x7a,
	0x37, 0xe7, 0x3b, 0xf6, 0xcc, 0x39, 0xdf, 0xf7, 0xcd, 0xd1, 0xc0, 0xe5, 0x5a, 0x70, 0xc5, 0x03,
	0x1e, 0xdf, 0xdc, 0x09, 0xbe, 0x42, 0x31, 0x36, 0xb1, 0xeb, 0x94, 0xb0, 0xbf, 0x85, 0x93, 0x57,
	0x28, 0x25, 0x8d, 0xd0, 0xfd, 0x14, 0x06, 0x49, 0xbe, 0xbc, 0x0d, 0x3d, 0x6b, 0x68, 0x8d, 0x3a,
	0xa4, 0x02, 0xdc, 0x27, 0xe0, 0x04, 0xf7, 0x18, 0xac, 0x16, 0x59, 0xe2, 0xd9, 0x43, 0x6b, 0xd4,
	0x23, 0xbb, 0xd8, 0x1d, 0xc2, 0xe9, 0x9a, 0x6e, 0x5f, 0x72, 0x1a, 0x3e, 0xa7, 0x8a, 0x7a, 0x9d,
	0xa1, 0x35, 0x3a, 0x23, 0x75, 0xc8, 0x75, 0xa1, 0xbb, 0x8c, 0x69, 0xe4, 0x75, 0xcd, 0x9f, 0x66,
	0xed, 0xbf, 0x81, 0xc7, 0xcf, 0x32, 0x75, 0xcf, 0x05, 0xfb, 0x09, 0xc3, 0xdb, 0x74, 0xc9, 0xdd,
	0x09, 0x5c, 0xbc, 0x61, 0x92, 0xa9, 0x0a, 0x7e, 0xcd, 0x57, 0x98, 0x16, 0xc5, 0x1c, 0xcc, 0xb9,
	0x4f, 0xe1, 0x9c, 0x66, 0xea, 0xbe, 0xfd, 0x8b, 0x2e, 0x71, 0x40, 0x0e, 0xa5, 0xfc, 0x3f, 0x6d,
	0xb8, 0x5c, 0x60, 0x1a, 0x16, 0x7d, 0x13, 0xdc, 0x64, 0x28, 0xd5, 0x7c, 0x32, 0x35, 0x3d, 0xc6,
	0x0c, 0x53, 0x55, 0x10, 0x30, 0x20, 0xbb, 0x58, 0xb3, 0xa3, 0xf8, 0x9a, 0x05, 0xdf, 0xd3, 0x04,
	0x8b, 0xdd, 0x2b, 0x20, 0x67, 0x40, 0x28, 0xa6, 0x18, 0x4f, 0x6f, 0x43, 0xc3, 0x40, 0x8f, 0xd4,
	0x21, 0xcd, 0x40, 0xa8, 0xc9, 0xe9, 0x1a, 0x72, 0xcc, 0x7a, 0xc7, 0x4a, 0xaf, 0x62, 0xa5, 0xc1,
	0x73, 0xbf, 0xc5, 0xf3, 0x13, 0x70, 0x24, 0xa6, 0xea, 0x59, 0x18, 0x0a, 0xef, 0x24, 0xcf, 0x95,
	0xb1, 0xeb, 0xc1, 0x49, 0x22, 0xa3, 0xd7, 0xdb, 0x35, 0x7a, 0x8e, 0xa9, 0xae, 0x0c, 0xcb, 0x0c,
	0x4b, 0xd0, 0x1b, 0x54, 0x19, 0x96, 0xa0, 0xfb, 0x35, 0x38, 0x9a, 0x20, 0xcd, 0xbd, 0x07, 0x43,
	0x6b, 0x74, 0x3a, 0xf1, 0xc6, 0xa5, 0x33, 0xc6, 0x4d, 0x6d, 0xc8, 0xee, 0x4b, 0xff, 0x57, 0x0b,
	0xae, 0x1a, 0xfc, 0xc9, 0x35, 0x4f, 0x25, 0x4e, 0x27, 0x73, 0x7d, 0x94, 0xcc, 0x82, 0x00, 0xa5,
	0x34, 0xfc, 0x39, 0xa4, 0x0c, 0x75, 0x06, 0x85, 0x98, 0xf1, 0x10, 0x0b, 0xf7, 0x94, 0xa1, 0x7b,
	0x05, 0x7d, 0x14, 0xe2, 0x95, 0x8c, 0x0c, 0x6b, 0x03, 0x52, 0x44, 0x9a, 0x52, 0x81, 0x9b, 0x8c,
	0x09, 0xd4, 0x95, 0x18, 0xde, 0x1c, 0x52, 0x87, 0xfc, 0xbf, 0x3b, 0xe0, 0x12, 0x8c, 0x98, 0x54,
	0x28, 0x0a, 0x15, 0x67, 0x93, 0xa9, 0xde, 0x90, 0xaf, 0x0d, 0x11, 0x96, 0x39, 0xa9, 0x88, 0x1a,
	0xea, 0xda, 0xfb, 0xea, 0x46, 0x82, 0x67, 0x6b, 0xa3, 0x6e, 0x5e, 0x47, 0x05, 0x34, 0xb5, 0xef,
	0x1e, 0xd1, 0xbe, 0xb7, 0xaf, 0xfd, 0x67, 0x00, 0x02, 0x69, 0xb8, 0x50, 0x54, 0x65, 0xb2, 0x50,
	0xb5, 0x86, 0xb8, 0x9f, 0xc3, 0xa3, 0x25, 0x8b, 0x15, 0x8a, 0x19, 0x4f, 0xc3, 0x85, 0xd2, 0xe2,
	0x76, 0x46, 0x03, 0xd2, 0x04, 0xf5, 0x2e, 0x41, 0x26, 0xc4, 0x0f, 0xcb, 0xa5, 0x44, 0x65, 0x44,
	0xee, 0x90, 0x1a, 0xa2, 0xf3, 0x12, 0xa5, 0x64, 0x3c, 0xfd, 0x0e, 0xb7, 0x85, 0xd4, 0x35, 0x44,
	0xd7, 0x59, 0x44, 0xc6, 0x0b, 0x60, 0x36, 0xa8, 0x43, 0x66, 0x07, 0x19, 0x2e, 0x14, 0x17, 0x7a,
	0x04, 0x9c, 0xe6, 0x27, 0x54, 0x88, 0xae, 0x73, 0x23, 0xb6, 0x73, 0xc1, 0xb8, 0x60, 0x6a, 0x7b,
	0x1b, 0x7a, 0x67, 0xa6, 0x95, 0x26, 0xd8, 0x70, 0xd5, 0xa3, 0x07, 0xbb, 0xea, 0x67, 0x0b, 0xce,
	0x2b, 0x31, 0x4b, 0x4b, 0xcd, 0xfe, 0x57, 0x4b, 0x35, 0x19, 0xec, 0xb6, 0x19, 0xf4, 0x7f, 0xb7,
	0xe1, 0xfc, 0x5b, 0xa4, 0x42, 0x4d, 0x91, 0xaa, 0x9a, 0xa3, 0x8e, 0xcc, 0x85, 0xca, 0x39, 0x76,
	0xdb, 0x39, 0x4d, 0xe5, 0x3b, 0x87, 0x94, 0xaf, 0x8c, 0xa2, 0x09, 0xeb, 0xe6, 0xca, 0x37, 0xc0,
	0x96, 0x2e, 0xbd, 0xe3, 0xba, 0xf4, 0x8f, 0xe9, 0x72, 0xf2, 0x60, 0x5d, 0xfe, 0xb1, 0xe0, 0xa2,
	0xc6, 0xc9, 0xfb, 0x11, 0xe6, 0x0b, 0x78, 0x7c, 0x4f, 0xe5, 0x9c, 0x0a, 0xf5, 0x82, 0xb2, 0x38,
	0x13, 0x58, 0x5c, 0xf7, 0x16, 0xaa, 0x2d, 0xbc, 0xcc, 0x97, 0xa6, 0x8b, 0x9e, 0x21, 0xab, 0x0e,
	0xb5, 0xa7, 0x46, 0x7f, 0x7f, 0x6a, 0xfc, 0x66, 0xc3, 0xc5, 0x37, 0xa8, 0x9a, 0xd3, 0xff, 0x98,
	0xca, 0xad, 0x3b, 0x6e, 0xef, 0xdf, 0xf1, 0x77, 0x99, 0x20, 0x5f, 0xc2, 0x47, 0x31, 0x95, 0x6a,
	0x4e, 0x83, 0xd5, 0x8c, 0xa7, 0x32, 0x4b, 0x30, 0x57, 0xd9, 0x21, 0x7b, 0xb8, 0x3b, 0x06, 0x37,
	0xa1, 0x69, 0x46, 0xe3, 0x19, 0x4f, 0x12, 0xa6, 0x0a, 0x2f, 0xe7, 0x7d, 0x1e, 0xc8, 0xe8, 0xca,
	0x51, 0x06, 0x2f, 0x62, 0xfe, 0x76, 0xa6, 0x44, 0x6c, 0x84, 0x77, 0x48, 0x1d, 0xf2, 0xff, 0xb0,
	0xe1, 0xb2, 0x4e, 0xc8, 0xfb, 0x91, 0xf8, 0x1a, 0x9c, 0xe2, 0x31, 0x21, 0x8d, 0xc9, 0x4f, 0x27,
	0x1f, 0x57, 0xee, 0x2b, 0xcf, 0xde, 0x7d, 0xd2, 0xba, 0xaa, 0xbd, 0xbd, 0x61, 0xe7, 0xc3, 0x59,
	0xc2, 0xd2, 0x97, 0x2c, 0x61, 0xca, 0x4c, 0xb3, 0xdc, 0xf1, 0x0d, 0xec, 0x78, 0xeb, 0xfa, 0x0b,
	0xbd, 0xa7, 0x7e, 0xa2, 0x3c, 0x8f, 0xcb, 0x99, 0x5a, 0x87, 0x6a, 0x7e, 0x5a, 0xc4, 0xfc, 0xad,
	0x99, 0xaa, 0x95, 0x9f, 0x34, 0xe4, 0xff, 0x65, 0xc1, 0x55, 0x9d, 0xf1, 0x87, 0xcf, 0x8d, 0x77,
	0x7a, 0x4f, 0x34, 0xfc, 0xd6, 0x6d, 0xfb, 0xed, 0x3f, 0x38, 0xca, 0xff, 0xc5, 0x82, 0x4f, 0x9a,
	0x0d, 0x7c, 0x90, 0xe9, 0x3b, 0x9d, 0xfc, 0xf8, 0x34, 0x62, 0x6a, 0x1c, 0xf0, 0x10, 0xc7, 0x9c,
	0x8e, 0x03, 0x9e, 0xdc, 0xa8, 0xf0, 0x8e, 0xa6, 0xab, 0x1b, 0x95, 0xdd, 0x61, 0xb2, 0xb9, 0xce,
	0xb9, 0xbb, 0x8e, 0xf8, 0x4d, 0x69, 0x9c, 0xbb, 0xbe, 0x59, 0x7d, 0xf5, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x92, 0x3a, 0x3d, 0xb5, 0xe8, 0x0a, 0x00, 0x00,
}
