// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/msg.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_SUCCESS Status = 0
	Status_ERROR   Status = 1
	Status_FATAL   Status = 2
)

var Status_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR",
	2: "FATAL",
}

var Status_value = map[string]int32{
	"SUCCESS": 0,
	"ERROR":   1,
	"FATAL":   2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c8c4aad43ef7e1fe, []int{0}
}

type RequestHeader struct {
	ServiceType          int32    `protobuf:"varint,1,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	ProtocolVer          int32    `protobuf:"varint,2,opt,name=protocolVer,proto3" json:"protocolVer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c4aad43ef7e1fe, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetServiceType() int32 {
	if m != nil {
		return m.ServiceType
	}
	return 0
}

func (m *RequestHeader) GetProtocolVer() int32 {
	if m != nil {
		return m.ProtocolVer
	}
	return 0
}

type RequestBody struct {
	Method               int32    `protobuf:"varint,1,opt,name=method,proto3" json:"method,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestBody) Reset()         { *m = RequestBody{} }
func (m *RequestBody) String() string { return proto.CompactTextString(m) }
func (*RequestBody) ProtoMessage()    {}
func (*RequestBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c4aad43ef7e1fe, []int{1}
}

func (m *RequestBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestBody.Unmarshal(m, b)
}
func (m *RequestBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestBody.Marshal(b, m, deterministic)
}
func (m *RequestBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestBody.Merge(m, src)
}
func (m *RequestBody) XXX_Size() int {
	return xxx_messageInfo_RequestBody.Size(m)
}
func (m *RequestBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestBody.DiscardUnknown(m)
}

var xxx_messageInfo_RequestBody proto.InternalMessageInfo

func (m *RequestBody) GetMethod() int32 {
	if m != nil {
		return m.Method
	}
	return 0
}

func (m *RequestBody) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RequestBody) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ResponseHeader struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=protocol.Status" json:"status,omitempty"`
	ServiceType          int32    `protobuf:"varint,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	ProtocolVer          int32    `protobuf:"varint,3,opt,name=protocolVer,proto3" json:"protocolVer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c4aad43ef7e1fe, []int{2}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_SUCCESS
}

func (m *ResponseHeader) GetServiceType() int32 {
	if m != nil {
		return m.ServiceType
	}
	return 0
}

func (m *ResponseHeader) GetProtocolVer() int32 {
	if m != nil {
		return m.ProtocolVer
	}
	return 0
}

type RspExceptionBody struct {
	ExceptionName        string   `protobuf:"bytes,1,opt,name=exceptionName,proto3" json:"exceptionName,omitempty"`
	StackTrace           string   `protobuf:"bytes,2,opt,name=stackTrace,proto3" json:"stackTrace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspExceptionBody) Reset()         { *m = RspExceptionBody{} }
func (m *RspExceptionBody) String() string { return proto.CompactTextString(m) }
func (*RspExceptionBody) ProtoMessage()    {}
func (*RspExceptionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c4aad43ef7e1fe, []int{3}
}

func (m *RspExceptionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspExceptionBody.Unmarshal(m, b)
}
func (m *RspExceptionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspExceptionBody.Marshal(b, m, deterministic)
}
func (m *RspExceptionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspExceptionBody.Merge(m, src)
}
func (m *RspExceptionBody) XXX_Size() int {
	return xxx_messageInfo_RspExceptionBody.Size(m)
}
func (m *RspExceptionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RspExceptionBody.DiscardUnknown(m)
}

var xxx_messageInfo_RspExceptionBody proto.InternalMessageInfo

func (m *RspExceptionBody) GetExceptionName() string {
	if m != nil {
		return m.ExceptionName
	}
	return ""
}

func (m *RspExceptionBody) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

type RspResponseBody struct {
	Method               int32    `protobuf:"varint,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspResponseBody) Reset()         { *m = RspResponseBody{} }
func (m *RspResponseBody) String() string { return proto.CompactTextString(m) }
func (*RspResponseBody) ProtoMessage()    {}
func (*RspResponseBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c4aad43ef7e1fe, []int{4}
}

func (m *RspResponseBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspResponseBody.Unmarshal(m, b)
}
func (m *RspResponseBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspResponseBody.Marshal(b, m, deterministic)
}
func (m *RspResponseBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspResponseBody.Merge(m, src)
}
func (m *RspResponseBody) XXX_Size() int {
	return xxx_messageInfo_RspResponseBody.Size(m)
}
func (m *RspResponseBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RspResponseBody.DiscardUnknown(m)
}

var xxx_messageInfo_RspResponseBody proto.InternalMessageInfo

func (m *RspResponseBody) GetMethod() int32 {
	if m != nil {
		return m.Method
	}
	return 0
}

func (m *RspResponseBody) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.Status", Status_name, Status_value)
	proto.RegisterType((*RequestHeader)(nil), "protocol.RequestHeader")
	proto.RegisterType((*RequestBody)(nil), "protocol.RequestBody")
	proto.RegisterType((*ResponseHeader)(nil), "protocol.ResponseHeader")
	proto.RegisterType((*RspExceptionBody)(nil), "protocol.RspExceptionBody")
	proto.RegisterType((*RspResponseBody)(nil), "protocol.RspResponseBody")
}

func init() { proto.RegisterFile("protocol/msg.proto", fileDescriptor_c8c4aad43ef7e1fe) }

var fileDescriptor_c8c4aad43ef7e1fe = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x6d, 0x09, 0x45, 0x06, 0xc1, 0x66, 0x0f, 0xa6, 0x27, 0x43, 0x1a, 0x0f, 0x44, 0x43,
	0x6b, 0xf0, 0x17, 0x00, 0xc1, 0x78, 0x30, 0x9a, 0x6c, 0xd1, 0xa8, 0xb7, 0x65, 0x3b, 0xc1, 0x06,
	0xda, 0x5d, 0xba, 0x5b, 0x23, 0x17, 0x7f, 0xbb, 0xa1, 0xed, 0x26, 0xa0, 0x07, 0x6e, 0xfb, 0xbe,
	0x99, 0xbe, 0xce, 0x7b, 0x40, 0x64, 0x2e, 0xb4, 0xe0, 0x62, 0x1d, 0xa6, 0x6a, 0x19, 0x94, 0x82,
	0x9c, 0x1a, 0xe6, 0x47, 0xd0, 0xa5, 0xb8, 0x29, 0x50, 0xe9, 0x07, 0x64, 0x31, 0xe6, 0xa4, 0x0f,
	0x1d, 0x85, 0xf9, 0x57, 0xc2, 0x71, 0xbe, 0x95, 0xe8, 0x59, 0x7d, 0x6b, 0xd0, 0xa4, 0xfb, 0x68,
	0xb7, 0x61, 0x3e, 0x7f, 0xc5, 0xdc, 0xb3, 0xab, 0x8d, 0x3d, 0xe4, 0xbf, 0x43, 0xa7, 0x36, 0x9d,
	0x88, 0x78, 0x4b, 0x2e, 0xc0, 0x49, 0x51, 0x7f, 0x8a, 0xb8, 0x76, 0xab, 0x15, 0xf1, 0xa0, 0xa5,
	0x93, 0x14, 0x45, 0xa1, 0x4b, 0x93, 0x06, 0x35, 0x72, 0x37, 0x91, 0x6c, 0xbb, 0x16, 0x2c, 0xf6,
	0x1a, 0x7d, 0x6b, 0x70, 0x46, 0x8d, 0xf4, 0x7f, 0xa0, 0x47, 0x51, 0x49, 0x91, 0x29, 0xac, 0x0f,
	0x1e, 0x80, 0xa3, 0x34, 0xd3, 0x85, 0x2a, 0xdd, 0x7b, 0x23, 0x37, 0x30, 0xa7, 0x04, 0x51, 0xc9,
	0x69, 0x3d, 0xff, 0x1b, 0xcd, 0x3e, 0x1a, 0xad, 0xf1, 0x3f, 0xda, 0x1b, 0xb8, 0x54, 0xc9, 0xd9,
	0x37, 0x47, 0xa9, 0x13, 0x91, 0x95, 0xf9, 0xae, 0xa0, 0x8b, 0x06, 0x3c, 0xb1, 0xb4, 0x2a, 0xad,
	0x4d, 0x0f, 0x21, 0xb9, 0x04, 0x50, 0x9a, 0xf1, 0xd5, 0x3c, 0x67, 0xbc, 0xfa, 0x79, 0x9b, 0xee,
	0x11, 0x7f, 0x0a, 0xe7, 0x54, 0x49, 0x13, 0xee, 0x58, 0x71, 0xa6, 0x1e, 0xfb, 0xa0, 0x9e, 0xeb,
	0x1b, 0x70, 0xaa, 0xd0, 0xa4, 0x03, 0xad, 0xe8, 0x65, 0x3a, 0x9d, 0x45, 0x91, 0x7b, 0x42, 0xda,
	0xd0, 0x9c, 0x51, 0xfa, 0x4c, 0x5d, 0x6b, 0xf7, 0xbc, 0x1f, 0xcf, 0xc7, 0x8f, 0xae, 0x3d, 0x19,
	0x7d, 0xdc, 0x2e, 0x13, 0x1d, 0x70, 0x11, 0x63, 0x20, 0x58, 0xc0, 0x45, 0x1a, 0xea, 0x78, 0xc1,
	0xb2, 0x55, 0xa8, 0x8b, 0x05, 0xa6, 0x9b, 0x21, 0x5f, 0x27, 0x98, 0xe9, 0xe1, 0x52, 0x84, 0xa6,
	0x82, 0x85, 0x53, 0xbe, 0xee, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x50, 0x28, 0x94, 0x56,
	0x02, 0x00, 0x00,
}
